name: Deploy Vite React App to Docker Server via Bastion

on:
  push:
    branches:
      - 여기에merge하면배포됨

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd runWithMate
          npm install

      - name: Build the Vite app
        run: |
          cd runWithMate
          npm run build

      - name: Build Docker image
        run: |
          cd runWithMate
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/runwithmate_front:latest .

      - name: Push Docker image
        run: |
          cd runWithMate
          docker push ${{ secrets.DOCKER_REGISTRY }}/runwithmate_front:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server via Bastion
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          BASTION_PRIVATE_KEY: ${{ secrets.BASTION_PRIVATE_KEY }}
        run: |
          echo "$BASTION_PRIVATE_KEY" > bastion_key.pem
          chmod 600 bastion_key.pem
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          # 포트 포워딩 설정
          ssh -o StrictHostKeyChecking=no -i bastion_key.pem -p 2090 -f -N -L 2222:${{ secrets.SERVER_IP }}:22 ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_IP }}
          
          # 최종 서버에 접근하여 Docker 작업 수행
          ssh -o StrictHostKeyChecking=no -i key.pem -p 2222 ${{ secrets.SERVER_USER }}@localhost << EOF
            docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/runwithmate_front:latest
            docker stop runwithmate_front || true
            docker rm runwithmate_front || true
            docker run -d --network server --name runwithmate_front ${{ secrets.DOCKER_REGISTRY }}/runwithmate_front:latest
          EOF
