name: Deploy Vite React App to k3s

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd runWithMate
          npm install

      - name: Build the Vite app
        run: |
          cd runWithMate
          npm run build

      - name: Build Docker image
        run: |
          cd runWithMate
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/runwithmate_front:latest .

      - name: Push Docker image
        run: |
          cd runWithMate
          docker push ${{ secrets.DOCKER_REGISTRY }}/runwithmate_front:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          chmod 600 kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to k3s
        env:
          KUBECONFIG: ~/.kube/config
        run: |
          kubectl rollout restart deployment/lgtu-back
